refactor(messages)!: Merge no-deprecated-property/parameter into no-deprecated-api
SAP/ui5-linter pull request #324
Opened 2024-09-26 16:12 UTC by RandomByte

Also sort all messages alphabetically

2024-09-26 16:16 UTC, RandomByte commented
@KlattG kindly review the user-facing messages in file "**messages.ts**" (ignore any other files).

The PR shows a large set of changes because I sorted the messages alphabetically. To see which changes I made to the actual content of the messages, see https://github.com/SAP/ui5-linter/pull/324/commits/117f44d843993f95fcbadb9cc3dfb1e7efa3580e

However, there were other changes to the messages in PRs https://github.com/SAP/ui5-linter/pull/320 and https://github.com/SAP/ui5-linter/pull/316

So I thought maybe it makes sense to review all messages together in this PR, especially since we won't add many more until the UI5 linter v1.0 release.

2024-09-27 07:33 UTC, d3xter666 approved these changes
LGTM

2024-09-27 13:40 UTC, KlattG requested changes

2024-09-27 13:40 UTC, KlattG commented on src/linter/messages.ts
> +			`As of version 1.110.0, parameter 'synchronizationMode' is obsolete and must be omitted. ` +
```suggestion
			`As of version 1.110.0, the 'synchronizationMode' parameter is obsolete and must be omitted. ` +
```

2024-09-27 13:40 UTC, KlattG commented on src/linter/messages.ts
> +			`{@link sap/ui/model/odata/v4/ODataModel#constructor See API reference}`,
```suggestion
			`{@link sap/ui/model/odata/v4/ODataModel#constructor See the API reference}`,
```

2024-09-27 13:40 UTC, KlattG commented on src/linter/messages.ts
> +			`Use of property deprecated property '${propertyName}'.` +
```suggestion
			`Use of deprecated property '${propertyName}'.` +
```

2024-09-27 13:40 UTC, KlattG commented on src/linter/messages.ts
> +			`Deprecated access of DataType-pseudo module '${moduleName}'`,
```suggestion
			`Deprecated access of DataType pseudo module '${moduleName}'`,
```

2024-09-27 13:40 UTC, KlattG commented on src/linter/messages.ts
> +			`Deprecated access of enum-pseudo module '${moduleName}'`,
```suggestion
			`Deprecated access of enum pseudo module '${moduleName}'`,
```

2024-09-27 13:40 UTC, KlattG commented on src/linter/messages.ts
> +			`Do not use global variables to access UI5 modules or API. ` +
```suggestion
			`Do not use global variables to access UI5 modules or APIs. ` +
```

2024-09-27 13:40 UTC, KlattG commented on src/linter/messages.ts
> +			`Parameter 'oConfig.async' must be set to true. ` +
```suggestion
			`The 'oConfig.async' parameter must be set to true. ` +
```

2024-09-27 13:40 UTC, KlattG commented on src/linter/messages.ts
> +			`{@link sap/ui/core/routing/Router#constructor See API reference}`,
```suggestion
			`{@link sap/ui/core/routing/Router#constructor See the API reference}`,
```

2024-09-27 13:40 UTC, KlattG commented on src/linter/messages.ts
> +		details: () => `Property 'async' must be either omitted or set to true. ` +
```suggestion
		details: () => `The 'async' property must be either omitted or set to true. ` +
```

2024-09-27 13:40 UTC, KlattG commented on src/linter/messages.ts
> +			`{@link sap.ui.core.Component#createComponent See API reference}`,
```suggestion
			`{@link sap.ui.core.Component#createComponent See the API reference}`,
```

2024-09-27 13:40 UTC, KlattG commented on src/linter/messages.ts
> +			`{@link sap.ui.model.odata.v2.ODataModel#createEntry See API reference}`,
```suggestion
		details: () => `Use the 'groupId' parameter instead. ` +
			`{@link sap.ui.model.odata.v2.ODataModel#createEntry See the API reference}`,
```

2024-09-27 13:40 UTC, KlattG commented on src/linter/messages.ts
> +			`{@link sap.ui.model.odata.v2.ODataModel#createEntry See API reference}`,
```suggestion
			`{@link sap.ui.model.odata.v2.ODataModel#createEntry See the API reference}`,
```

2024-09-27 13:40 UTC, KlattG commented on src/linter/messages.ts
> +			`Outdated spelling of bootstrap parameter: '${oldName}' should be written as '${newName}'`,
```suggestion
			`Outdated spelling of bootstrap parameter: '${oldName}'; should be written as '${newName}'`,
```

2024-09-27 14:54 UTC, flovogt approved these changes

2024-09-27 14:54 UTC, merged