fix: Check unmatched patterns
SAP/ui5-linter pull request #334
Opened 2024-10-01 08:28 UTC by d3xter666

JIRA: CPOUI5FOUNDATION-881

2024-10-01 12:04 UTC, d3xter666 commented on src/linter/linter.ts
> +	patternsMatch[pattern] = patternsMatch[pattern] ? patternsMatch[pattern] + 1 : 1;
Currently, not, but I was wondering whether this could serve us somehow...
I'll just use the Set. Thanks! It'd be quicker and simpler :)

2024-10-01 13:45 UTC, RandomByte requested changes

2024-10-01 13:45 UTC, RandomByte commented on src/linter/linter.ts
> +			` '${unmatchedPatterns.join("', '")}' did not match any resource!`);
```suggestion
		throw new Error(`Specified file ${unmatchedPatterns.length === 1 ? "pattern" : "patterns"}` +
			` '${unmatchedPatterns.join("', '")}' did not match any resource`);
```

2024-10-01 14:01 UTC, RandomByte approved these changes

2024-10-01 14:02 UTC, merged

2024-10-18 07:25 UTC, matz3 commented on src/linter/linter.ts
> +const matchedPatterns = new Set<string>();
Having this here as a singleton set will most probably cause issues when running multiple linting activities in the same process in parallel. We should think about moving it to an instance of the current linting activity, which might require some refactoring (e.g. turning this module into a class might help).