feat(cli): In case of errors, exit with code 1
SAP/ui5-linter pull request #41
Opened 2024-03-20 15:51 UTC by RandomByte

This change alignes UI5 linter with ESLint (see [1]):
* No errors, maybe warnings: Use exit code 0
* At least one error: Use exit code 1
* Unexpected error (typically caused by an exception): Use exit code 2

[1]: https://eslint.org/docs/latest/use/command-line-interface#exit-codes

2024-03-20 16:23 UTC, flovogt approved these changes

2024-03-20 16:26 UTC, matz3 requested changes
Isn't this a breaking change?

2024-03-21 14:22 UTC, RandomByte commented
> Isn't this a breaking change?

True, done

2024-03-21 14:50 UTC, flovogt commented
Please add also the jira CPOUI5FOUNDATION-823 to the commit message

2024-03-22 08:18 UTC, RandomByte commented
> Please add also the jira item id CPOUI5FOUNDATION-823 to the commit message

Done 👍

2024-03-22 08:34 UTC, flovogt approved these changes

2024-03-22 09:24 UTC, merged